# Generated by Django 2.2 on 2020-05-12 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='tags',
        ),
    ]
