# Generated by Django 2.2 on 2020-05-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_hotel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='avatar',
            field=models.TextField(),
        ),
    ]
